Spring:
  datasource:
   url: jdbc:sqlserver://rajatserver2.database.windows.net:1433;database=Azure-Employees;user=rajat1234@rajatserver2;password=rajatchaurasiya@123;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
   username: rajat1234
   password: rajatchaurasiya@123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
     
      
server:
  port: 9191